core/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('<view_name>/', views.InfoView.as_view(), name='info'),
    # TODO development serving
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('menu/', include('menu.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    # info url can override other apps unless below
    path('', include('core.urls')),
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.MenuListView.as_view(), name='menu'),
    path('<int:pk>/', views.MenuItemView.as_view(), name='detail'),
    path('specials/', views.SpecialsListView.as_view(), name='specials'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('cart_debug/', views.cart_debug, name='cart_debug')
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

orders/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone

MAX_ORDER_VOLUME = 20


class OrderInfo(models.Model):
    """
    Order object bound to user with cost function
    calculated with belonging OrderContents.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)

    total_cost = models.IntegerField(default=0)

    # State properties
    ordered = models.DateTimeField(
        'date order was placed', auto_now_add=True)
    cooked = models.DateTimeField(
        'date order was cooked', null=True, blank=True)
    delivered = models.DateTimeField(
        'date order was delivered', null=True, blank=True)

    def update_current_state(self):
        """
        When called, timing properties are gradually updated.
        """
        if self.cooked is None:
            self.cooked = timezone.now()
        else:
            self.delivered = timezone.now()
        self.save()


class OrderContents(models.Model):
    """
    A single MenuItem, its amount and corresponding order.
    """
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    menu_item = models.ForeignKey('menu.MenuItem', on_delete=models.CASCADE)
    amount = models.IntegerField(
        default=1,
        validators=[MaxValueValidator(MAX_ORDER_VOLUME), MinValueValidator(1)])
    cost = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.id is not None:
            self.order.total_cost -= self.cost
        self.cost = self.amount * self.menu_item.price
        self.order.total_cost += self.cost
        self.order.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.order.total_cost -= self.cost
        self.order.save()
        super().delete(*args, **kwargs)

orders/forms.py
from django import forms


class AmountForm(forms.Form):
    amount = forms.IntegerField(label='Amount')

orders/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from .models import OrderInfo, OrderContents
from menu.models import MenuItem
from accounts.forms import CustomOrderForm


def shopping_cart(request):
    template_name = 'orders/shopping_cart.html'
    cart_contents = build_cart_contents(request.session.get('cart', {}))
    return render(request, template_name, cart_contents)


def checkout(request):
    # TODO there also will be a register option for anons
    cart = request.session.get('cart', {})
    if len(cart) == 0:
        messages.error(request, "Your cart is empty.")
        return HttpResponseRedirect(reverse('orders:shopping_cart'))

    if request.user.is_authenticated:
        instance = request.user
    else:
        instance = None

    if request.method == 'POST':
        form = CustomOrderForm(request.POST, instance=instance)

        if form.is_valid():
            user = form.save()
            if request.user.is_anonymous:
                # don't register a guest user
                user.set_unusable_password()
                user.is_guest = True
                user.save()

            write_order_to_db(user, cart)
            flush_cart(request.session)
            return render(request, 'orders/success.html')
    else:
        form = CustomOrderForm(instance=instance)

    return render(request, 'orders/checkout.html', {'form': form})


def flush_cart(session):
    session['cart'].clear()
    session['cart_cost'] = 0
    session.modified = True


def build_cart_contents(cart_dict):
    contents = []
    for item, amount in cart_dict.items():
        current_item = MenuItem.objects.get(pk=item)
        cost = current_item.price * amount
        contents.append({
            'id': current_item.id,
            'name': current_item.name,
            'price': current_item.price,
            'amount': amount,
            'cost': cost
        })
    return {'contents': contents}


def write_order_to_db(user, cart):
    new_order = OrderInfo.objects.create(user=user)
    for item, amount in cart.items():
        menu_item = MenuItem.objects.get(pk=item)
        OrderContents.objects.create(
            order=new_order, menu_item=menu_item, amount=amount)

orders/templates/orders/checkout.html
{% extends "base.html" %}
{% block title %}
  Checkout
{% endblock %}
{% block content %}
<div>
  This is a checkout page.
</div>
{% if form.errors %}
<p>Some error occurred.</p>
{% endif %}
<form method="post" action="{% url 'orders:checkout' %}">
{% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="Place order">
</form>
{% endblock %}

orders/templates/orders/shopping_cart.html
{% extends "base.html" %}
{% block title %}
  Shopping cart
{% endblock %}
{% block head %}
  {% load static %}
  <script type="text/javascript" src="{% static 'menu/menu_script.js' %}" defer></script>
  <script type="text/javascript" src="{% static 'orders/orders_script.js' %}" defer></script>
  <script type="text/javascript">
    const update_cart_url = "{% url 'menu:update_cart' %}"
  </script>
  <link rel="stylesheet" href="{% static 'orders/shopping_cart_style.css' %}">
{% endblock %}
{% block content %}
<div id="table-container">
  {% if contents %}
   <table id="shopping-cart-table">
     <tbody>
      {% for item in contents %}
      <tr class="menu-item">
          <td class="item-name">
            {{ item.name }}
          </td>
          <td class="item-price">
            {{ item.price }}
          </td>
          <td class="change-amount decrease" data-action="decrease"></td>
          <td class="current-amount" data-item_id="{{ item.id }}">
            {{ item.amount }}
          </td>
          <td class="change-amount increase" data-action="increase"></td>
          <td class="item-cost">
            {{ item.cost }}
          </td>
          <td class="change-amount" data-action="remove">
            <img src="{% static 'menu/trash.png' %}" alt="Remove" class="icons">
          </td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">
          <a href="{% url 'orders:checkout' %}">
            Checkout
          </a>
        </td>
        <td colspan="3">Total:</td>
        <td id="food-cost">{{ request.session.cart_cost }}</td>
      </tr>
    </tfoot>
  </table>
  <div
  </div>
  {% else %}
    <p>Your shopping cart is empty.</p>
  {% endif %}
</div>
{% endblock %}

orders/templates/orders/success.html
{% extends "base.html" %}
{% block title %}
  Success
{% endblock %}
{% block content %}
<div id="result">
  Your order was placed.
</div>
{% endblock %}