core/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('<view_name>/', views.InfoView.as_view(), name='info'),
    # TODO development serving
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('menu/', include('menu.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    # info url can override other apps unless below
    path('', include('core.urls')),
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.MenuListView.as_view(), name='menu'),
    path('<int:pk>/', views.MenuItemView.as_view(), name='detail'),
    path('specials/', views.SpecialsListView.as_view(), name='specials'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('cart_debug/', views.cart_debug, name='cart_debug')
]

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator

# TODO actual img
DEFAULT_ITEM_IMG = 'menu_items/default.png'
DEFAULT_SPECIAL_IMG = 'menu_specials/default.png'


class MenuItem(models.Model):
    name = models.CharField(max_length=64, unique=True)
    price = models.IntegerField(validators=[MinValueValidator(1)])
    image = models.ImageField(
        upload_to='menu_items/',
        default=DEFAULT_ITEM_IMG)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class MenuSpecial(models.Model):
    """
    Placeholder model.
    """
    name = models.CharField(max_length=64, unique=True)
    image = models.ImageField(
        upload_to='menu_specials/',
        default=DEFAULT_SPECIAL_IMG)
    available = models.BooleanField(default=True)

menu/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import (
    HttpResponseRedirect, JsonResponse, HttpResponseBadRequest)
from django.urls import reverse

from .models import MenuItem, MenuSpecial

UPD_ACTIONS = {
    'increase': 1,
    'decrease': -1,
    'remove': None
}


class ListAvailableItems(generic.ListView):
    def get_queryset(self):
        return self.model.objects.exclude(available=False)


class MenuListView(ListAvailableItems):
    template_name = 'menu/index.html'
    model = MenuItem


class MenuItemView(generic.DetailView):
    template_name = 'menu/detail.html'
    model = MenuItem

    def get_object(self):
        pk = self.kwargs['pk']
        return get_object_or_404(MenuItem, pk=pk, available=True)


class SpecialsListView(ListAvailableItems):
    template_name = 'menu/specials.html'
    model = MenuSpecial


def cart_debug(request):
    """
    """
    if not request.user.is_admin:
        return HttpResponseRedirect(
            reverse('menu:menu'))
    print(request.session['cart'])
    print(request.session['cart_cost'])

    del request.session['cart']
    request.session['cart_cost'] = 0

    return HttpResponseRedirect(
        reverse('menu:menu'))


def update_cart(request):
    if request.method != 'GET':
        return HttpResponseRedirect(
            reverse('menu:menu'))

    # TODO '' goes through and raises exception, so 'or None' is needed
    item_id = request.GET.get('item_id') or None
    menuitem = get_object_or_404(MenuItem, pk=item_id)

    cart = request.session.setdefault('cart', {})
    key = item_id

    action = request.GET.get('action', '')
    try:
        amount_to_add = UPD_ACTIONS[action] or -cart[key]
    except(KeyError):
        return HttpResponseBadRequest()
    # TODO - a reasonable upper limit

    new_amount = cart.setdefault(key, 0) + amount_to_add
    if new_amount < 0:
        # can't lower zero amount
        return HttpResponseBadRequest()
    elif new_amount == 0:
        cost_change = -(cart[key] * menuitem.price)
        cart.pop(key)
    else:
        cost_change = amount_to_add * menuitem.price
        cart[key] = cart[key] + amount_to_add

    new_cost = request.session['cart_cost'] = request.session.setdefault(
        'cart_cost', 0) + cost_change

    request.session.modified = True

    return JsonResponse({'new_cost': new_cost})

menu/templates/menu/detail.html
{% extends "base.html" %}
{% block title %}
{{ menuitem.name }}
{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'menu/menu_detail_style.css' %}">
<script type="text/javascript" src="{% static 'menu/menu_script.js' %}" defer></script>
<script type="text/javascript">
  const update_cart_url = "{% url 'menu:update_cart' %}"
</script>
{% endblock %}
{% block content %}
{% load cart_lookup %}
<div class="menu-item">
  <div class="left-column">
    <div class="menu-item-image">
      <img src="{{ menuitem.image.url }}" alt="{{ menuitem.name }}">
    </div>
  </div>
  <div class="right-column">
    <div class="menu-item-info">
      <span class="menu-item-name">{{ menuitem.name }}</span>
      <span class="menu-item-price">{{ menuitem.price }}</span>
    </div>
    <div class="item-amount">
      <div class="change-amount decrease" data-action="decrease"></div>
      <div class="current-amount" data-item_id="{{ menuitem.id }}">
        <span>{{ request.session|get_cart_item:menuitem.id }}</span>
      </div>
      <div class="change-amount increase" data-action="increase"></div>
    </div>
    <div class="item-description">
      <span>Description goes here.</span>
    </div>
  </div>
</div>
{% endblock %}

menu/templates/menu/index.html
{% extends "base.html" %}
{% block title %}
Menu
{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'menu/menu_list_style.css' %}">
<script type="text/javascript" src="{% static 'menu/menu_script.js' %}" defer></script>
<script type="text/javascript" src="{% static 'menu/menu_list_script.js' %}" defer></script>
<script type="text/javascript">
  const update_cart_url = "{% url 'menu:update_cart' %}"
</script>
{% endblock %}
{% block content %}
<ul id="menu-items-list">
  {% load cart_lookup %}
  {% for menuitem in menuitem_list %}
  <li>
    <div class="menu-item">
      <div class="menu-item-card">
        <a href="{% url 'menu:detail' menuitem.id %}">
          <div class="menu-item-image">
            <img src="{{ menuitem.image.url }}" alt="{{ menuitem.name }}">
          </div>
          <div class="menu-item-info">
            <span class="menu-item-name">{{ menuitem.name }}</span>
            <span class="menu-item-price">{{ menuitem.price }}</span>
          </div>
        </a>
      </div>
      <div class="change-amount item-add-to-cart" data-action="increase">
        <img src="{% static 'menu/add_to_cart.png' %}" alt="Add to Cart" class="icons">
      </div>
      <div class="item-amount">
        <div class="change-amount" data-action="remove">
          <img src="{% static 'menu/trash.png' %}" alt="Remove" class="icons">
        </div>
        <div class="change-amount decrease" data-action="decrease"></div>
        <div class="current-amount" data-item_id="{{ menuitem.id }}">
          <span>{{ request.session|get_cart_item:menuitem.id }}</span>
        </div>
        <div class="change-amount increase" data-action="increase"></div>
      </div>
    </div>
  </li>
  {% empty %}
  <li>No items in menu :(</li>
  {% endfor %}
</ul>
{% endblock %}

menu/templates/menu/specials.html
{% extends "base.html" %}
{% block title %}
Specials
{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'menu/specials_style.css' %}">
{% endblock %}
{% block content %}
<ul id="menu-specials-list">
  {% for menuspecial in menuspecial_list %}
  <li>
    <div class="menu-special">
      <div class="menu-special-image">
        <img src="{{ menuspecial.image.url }}" alt="{{ menuspecial.name }}">
      </div>
      <div class="menu-special-name">
        {{menuspecial.name}}
      </div>
    </div>
  </li>
  {% empty %}
  <li>No specials available right now</li>
  {% endfor %}
</ul>
{% endblock %}