accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    CustomPasswordChangeView, CustomLoginView, profile, registration)

app_name = 'accounts'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('register/', registration, name='register'),
    path('profile/', profile, name='profile'),
    path('password_change/', CustomPasswordChangeView.as_view(),
         name='password_change'),
]

core/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('<view_name>/', views.InfoView.as_view(), name='info'),
    # TODO development serving
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('menu/', include('menu.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    # info url can override other apps unless below
    path('', include('core.urls')),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

core/models.py
from django.db import models

from string import capwords

TEMPLATES_FOLDER = 'core/info_sub/'
DEFAULT_TEMPLATE = 'default_info'


class InfoViewTemplate(models.Model):
    view_name = models.CharField(max_length=64, unique=True)
    title = models.CharField(max_length=64, unique=True, blank=True)
    template_name = models.CharField(max_length=64, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if self.title == '':
            self.title = capwords(self.view_name)
        if self.template_name == '':
            self.template_name = DEFAULT_TEMPLATE
        self.template_name = f'{TEMPLATES_FOLDER}{self.template_name}.html'
        super().save(*args, **kwargs)

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import InfoViewTemplate


def index(request):
    """
    Index page.
    """
    template_name = 'core/index.html'
    return render(request, template_name)


class InfoView(generic.DetailView):
    template_name = 'core/info.html'
    model = InfoViewTemplate

    def get_object(self):
        view_name = self.kwargs['view_name']
        return get_object_or_404(InfoViewTemplate, view_name=view_name)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    Welcome!
    {% endblock %}
  </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'core/style.css' %}">
  {# TODO for development only #}
  <!-- <script type="text/javascript" src="{% static 'core/live.js' %}" defer></script> -->
  {% block head %}
  {% endblock %}
</head>

<body>
  <header>
    <nav id="main-bar">
      <ul>
        <li>
          <a href="{% url 'core:index' %}">
            <img src="{% static 'core/koala.png' %}" alt="Home" class="icons">
          </a>
        </li>
        {% for view in navbar_views %}
        <li {% if view.url == request.path %} class="active" {% endif %}>
          <a href="{{ view.url }}">
            <span>{{ view.title }}</span>
          </a>
        </li>
        {% endfor %}
        <li id="user-section">
          <div id="cart">
            <a href="{% url 'orders:shopping_cart' %}">
              <img src="{% static 'core/cart.png' %}" alt="Shopping cart" class="icons">
              <span id="cart-cost">{{ request.session.cart_cost|default:"0" }}</span>
            </a>
          </div>
          <div id="profile">
            <a href="{% url 'accounts:profile' %}">
              <img src="{% static 'core/profile.png' %}" alt="Profile" class="icons">
            </a>
          </div>
        </li>
      </ul>
    </nav>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
        <span>{{ message }}</span>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
    <div>Copyright whatever</div>
  </footer>
</body>

</html>

core/templates/delivery.html
{% extends "base.html" %}
{% block title %}
  Delivery info
{% endblock %}
{% block content %}
<div>
  Here we have some info about delivery services.
</div>
{% endblock %}